name: Scrape IDX Suspension and Submit to Database

on:
  schedule:
    - cron: "0 3 * * *" # Runs at 10:00 AM UTC+7 every day
  workflow_dispatch:

jobs:
  run_scraper_and_submit:
    runs-on: ubuntu-latest

    env:
      PROXY : ${{ secrets.PROXY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraping script for all news source
        run: python pipeline.py 

      - name: Pull changes
        run: git pull origin main

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -m "Updated IDX Suspension" --allow-empty)
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
